apiVersion: v2
appVersion: 0.2.1
description: A prometheus exporter for the Andrew & Arnold CHAOS API
name: aaisp-exporter
version: 0.2.3
kubeVersion: ">=1.16.0-0"
keywords:
  - aaisp-exporter
home: https://github.com/nikdoof/helm-charts/tree/master/charts/aaisp-exporter
sources:
  - https://github.com/nikdoof/aaisp-chaos
maintainers:
  - name: nikdoof
    email: andy@tensixtyone.com
dependencies:
  - name: common
    repository: https://nikdoof.github.io/helm-charts/
    version: 4.5.3
