---
{{- if not (.Values.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "idrac6.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "idrac6.name" . }}
    helm.sh/chart: {{ include "idrac6.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ include "idrac6.name" . }}
type: Opaque
data:
  idrac.host: {{ .Values.idrac.host | b64enc }}
  idrac.username: {{ .Values.idrac.username | b64enc }}
  idrac.password: {{ .Values.idrac.password | b64enc }}
{{- end }}
