#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: domistyle/idrac6
  # -- image tag
  tag: v0.5
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [idrac6 documentation](https://github.com/DomiStyle/docker-idrac6).
# @default -- See below
env:
  # -- iDRAC hostname to connect to
  #IDRAC_HOST:
  # -- iDRAC Username to use
  #IDRAC_USER: root
  # -- iDRAC password to use
  #IDRAC_PASSWORD: calvin
  # -- iDRAC HTTP port
  IDRAC_PORT: 443
  # -- Enable keycode hack
  IDRAC_KEYCODE_HACK: 'false'

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5800
      vnc:
        port: 5900

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # -- allows caching of the required JARs in persistent storage, and allows for quicker connections.
  # @default -- See values.yaml
  app:
    enabled: false
    mountPath: /app
  # -- Virtual media that can be connected to the iDRAC.
  # @default -- See values.yaml
  vmedia:
    enabled: false
    mountPath: /vmedia
  # -- Screenshots took from the iDRAC client.
  # @default -- See values.yaml
  screenshots:
    enabled: false
    mountPath: /screenshots
