
{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "antennas.harcodedValues" -}}
  {{/* Append the configMap volume to the volumes */}}
  persistence:
    antennas-config:
      enabled: true
      type: "configMap"
      name: "{{ include "common.names.fullname" . }}-config"
      mountPath: "/antennas/config/config.yml"
      subPath: "config.yml"
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "antennas.harcodedValues" . | fromYaml) -}}

{{ include "common.all" . }}
