{
 "title": "HG612",
 "tags": [
  "hg612",
  "hg612-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(dsl_status, host)" } }
  ]
 },
 "panels": [
  {
   "title": "DSL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (host) (dsl_status{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Current Sync Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (host) (dsl_down_current_rate{host=\"$host\"})",
     "legendFormat": "Downstream"
    },
    {
     "expr": "avg by (host) (dsl_up_current_rate{host=\"$host\"})",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "Sync Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "avg by (host) (dsl_down_current_rate{host=\"$host\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "avg by (host) (dsl_down_max_rate{host=\"$host\"})",
     "legendFormat": "Max Attainable"
    },
    {
     "expr": "avg by (host) (dsl_up_current_rate{host=\"$host\"}) * -1",
     "legendFormat": "Up"
    },
    {
     "expr": "avg by (host) (dsl_up_max_rate{host=\"$host\"}) * -1",
     "legendFormat": "Max Attainable"
    }
   ]
  },
  {
   "title": "DSL Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (host) (increase(dsl_down_crc{host=\"$host\"}[$__rate_interval])) * -1",
     "legendFormat": "CRC Down"
    },
    {
     "expr": "sum by (host) (increase(dsl_up_crc{host=\"$host\"}[$__rate_interval]))",
     "legendFormat": "CRC Up"
    },
    {
     "expr": "sum by (host) (increase(dsl_down_fec{host=\"$host\"}[$__rate_interval])) * -1",
     "legendFormat": "FEC Down"
    },
    {
     "expr": "sum by (host) (increase(dsl_up_fec{host=\"$host\"}[$__rate_interval]))",
     "legendFormat": "FEC Up"
    },
    {
     "expr": "sum by (host) (increase(dsl_down_hec{host=\"$host\"}[$__rate_interval])) * -1",
     "legendFormat": "HEC Down"
    },
    {
     "expr": "sum by (host) (increase(dsl_up_hec{host=\"$host\"}[$__rate_interval]))",
     "legendFormat": "HEC Up"
    }
   ]
  }
 ]
}