{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "plex-exporter.harcodedValues" -}}
args:
  {{- if .Values.plex.autodiscover -}}
  - "--auto-discover"
  {{- else -}}
  - "--plex-server"
  - "{{ .Values.plex.server }}"
  {{- end -}}
  {{- if .Values.plex.token -}}
  - "--token"
  - "{{ .Values.plex.token }}"
  {{- end -}}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "plex-exporter.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
