{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "plex-exporter.harcodedValues" -}}
args:
  {{ if .Values.plex.server }}
  - "--plex-server"
  - "{{ .Values.plex.server }}"
  {{ else }}
  - "--auto-discover"
  {{ end }}
  {{ if .Values.plex.token }}
  - "--token"
  - "{{ .Values.plex.token }}"
  {{ end }}
  {{ if .Values.plex.loglevel }}
  - "--log-level"
  - "{{ .Values.plex.loglevel }}"
  {{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "plex-exporter.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
