#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: granra/plex_exporter
  # -- image tag
  tag: v0.2.3
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [plex-exporter documentation](https://github.com/nikdoof/plex-chaos/tree/master/cmd/plex_exporter).
# @default -- See below
env: {}

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
      metrics:
        enabled: true
        protocol: TCP
        port: 9594

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

plex:
  # -- Manual server address of your Plex server, as a URL, including the port
  server:
  # -- Authentication token to connect to your Plex instance
  token:
  # -- Enable autodiscover using plex.tv
  autodiscover: true
  # -- Logging level
  # loglevel: info

metrics:
  # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
  # @default -- See values.yaml
  enabled: false
  serviceMonitor:
    interval: 1m
    scrapeTimeout: 30s
    labels: {}
  # -- Enable and configure Prometheus Rules for the chart under this key.
  # @default -- See values.yaml
  prometheusRule:
    enabled: false
    labels: {}
    # -- Configure additionial rules for the chart under this key.
    # @default -- See prometheusrules.yaml
    rules:
      - alert: PlexExporterAbsent
        annotations:
          description: Plex Exporter has disappeared from Prometheus service discovery.
          summary: Plex Exporter is down.
        expr: |
          absent(up{job=~".*{{ include "common.names.fullname" . }}.*"} == 1)
        for: 5m
        labels:
          severity: critical

